### ISSUE TITLE
New Company and Edit Company Forms generate warnings

### ISSUE THREAD

**Issue by mattpage** [mattpage/pdx-tech#1]
bundle.js:17637 Warning: Unknown props `anyTouched`, `asyncValidate`, `asyncValidating`, `blur`, `change`, `destroy`, `dirty`, `dispatch`, `error`, `handleSubmit`, `initialize`, `initialized`, `initialValues`, `invalid`, `pristine`, `reset`, `submitting`, `submitFailed`, `submitSucceeded`, `touch`, `untouch`, `valid`, `warning`, `pure`, `validate`, `triggerSubmit`, `autofill`, `clearSubmit`, `clearSubmitErrors`, `clearAsyncError`, `submit`, `array`, `createCompany` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by ModalDialog)
    in ModalDialog (created by Modal)
    in Transition (created by Fade)
    in Fade (created by Modal)
    in div (created by Modal)

**Comment by leheinlein** [comment]
Fixed in my branch
